import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { OnboardingProvider } from "./context/MyContext";
import Footer from "./components/Footer";
import { NextAuthProvider } from "./Providers";
const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <OnboardingProvider>
            <Nav />
            {children}
            <Footer />
          </OnboardingProvider>
        </body>
      </NextAuthProvider>
    </html>
  );
}
