const products = [
  {
    name: "Chicken Manjoorion",
    price: 15.99,
    imgSrc: "/img/c1.png",
    description: "Exquisite chicken",
    category: "Chicken",
  },
  {
    name: "Chicken Kebab",
    price: 12.99,
    imgSrc: "/img/c3.png",
    description: "Grilled kebabs",
    category: "Chicken",
  },
  {
    name: "Fried Chicken",
    price: 13.99,
    imgSrc: "/img/c4.png",
    description: "Crispy delight",
    category: "Chicken",
  },
  {
    name: "Chicken Kebab Plate",
    price: 17.99,
    imgSrc: "/img/c6.png",
    description: "Abundant kebabs",
    category: "Chicken",
  },
  {
    name: "Broasted Chicken",
    price: 16.99,
    imgSrc: "/img/c7.png",
    description: "Classic broaster",
    category: "Chicken",
  },
  {
    name: "Cherry",
    price: 3.99,
    imgSrc: "/img/f8.png",
    description: "Red cherries",
    category: "Fruits",
  },
  {
    name: "Pineapple",
    price: 2.99,
    imgSrc: "/img/f2.png",
    description: "Juicy fruit",
    category: "Fruits",
  },
  {
    name: "Banana",
    price: 1.99,
    imgSrc: "/img/f9.png",
    description: "Ripe bananas",
    category: "Fruits",
  },
  {
    name: "Pomegranate",
    price: 4.99,
    imgSrc: "/img/f6.png",
    description: "Juicy seeds",
    category: "Fruits",
  },
  {
    name: "Strawberries",
    price: 5.99,
    imgSrc: "/img/f5.png",
    description: "Sweet berries",
    category: "Fruits",
  },
  {
    name: "Raspberry",
    price: 3.49,
    imgSrc: "/img/f7.png",
    description: "Red fruits",
    category: "Fruits",
  },
  {
    name: "Watermelon",
    price: 6.99,
    imgSrc: "/img/f10.png",
    description: "Refreshing melon",
    category: "Fruits",
  },
  {
    name: "Lemon",
    price: 2.49,
    imgSrc: "/img/f12.png",
    description: "Sour citrus",
    category: "Fruits",
  },
  {
    name: "Blueberries",
    price: 4.99,
    imgSrc: "/img/f3.png",
    description: "Tiny blues",
    category: "Fruits",
  },
  {
    name: "Concord Grapes",
    price: 3.99,
    imgSrc: "/img/f4.png",
    description: "Sweet grapes",
    category: "Fruits",
  },
  {
    name: "Pepsi",
    price: 1.99,
    imgSrc: "/img/d2.png",
    description: "Refreshing cola",
    category: "Soft Drinks",
  },
  {
    name: "Cocktail",
    price: 3.49,
    imgSrc: "/img/d4.png",
    description: "Mixed drink",
    category: "Soft Drinks",
  },
  {
    name: "Coca Cola",
    price: 2.99,
    imgSrc: "/img/d8.png",
    description: "Classic cola",
    category: "Soft Drinks",
  },
  {
    name: "Sprite",
    price: 2.49,
    imgSrc: "/img/d5.png",
    description: "Bubbly soda",
    category: "Soft Drinks",
  },
  {
    name: "Red Bull",
    price: 3.99,
    imgSrc: "/img/d1.png",
    description: "Energy boost",
    category: "Soft Drinks",
  },
  {
    name: "Fanta Orange",
    price: 1.99,
    imgSrc: "/img/d6.png",
    description: "Orange soda",
    category: "Soft Drinks",
  },
  {
    name: "Monster Energy",
    price: 2.99,
    imgSrc: "/img/d3.png",
    description: "Powerful drink",
    category: "Soft Drinks",
  },
  {
    name: "Strawberry",
    price: 4.99,
    imgSrc: "/img/i5.png",
    description: "Creamy treat",
    category: "Icecreams",
  },
  {
    name: "Coco Vanilla",
    price: 3.99,
    imgSrc: "/img/i2.png",
    description: "Coconut delight",
    category: "Icecreams",
  },
  {
    name: "Strawberry Vanilla",
    price: 5.99,
    imgSrc: "/img/i7.png",
    description: "Fruity delight",
    category: "Icecreams",
  },
  {
    name: "Chocolate",
    price: 4.49,
    imgSrc: "/img/i1.png",
    description: "Sweet cocoa",
    category: "Icecreams",
  },
  {
    name: "Harlequin",
    price: 6.99,
    imgSrc: "/img/i4.png",
    description: "Colorful treat",
    category: "Icecreams",
  },
  {
    name: "Lobster",
    price: 19.99,
    imgSrc: "/img/fish2.png",
    description: "Delicious seafood",
    category: "Fish",
  },
  {
    name: "Butter Chicken",
    price: 14.99,
    imgSrc: "/img/cu4.png",
    description: "Rich curry",
    category: "Curry",
  },
  {
    name: "Tilapia",
    price: 15.99,
    imgSrc: "/img/fi3.png",
    description: "Roasted Tilapia",
    category: "Fish",
  },
  {
    name: "Chicken Fried Rice",
    price: 11.99,
    imgSrc: "/img/r3.png",
    description: "Savory rice",
    category: "Rice",
  },
  {
    name: "Lighter Fried Rice",
    price: 10.99,
    imgSrc: "/img/r2.png",
    description: "Light rice",
    category: "Rice",
  },
  {
    name: "Shrimp Fried Rice",
    price: 12.99,
    imgSrc: "/img/r1.png",
    description: "Seafood rice",
    category: "Rice",
  },
  {
    name: "Classic Pork Fried Rice",
    price: 11.99,
    imgSrc: "/img/r4.png",
    description: "Porky delight",
    category: "Rice",
  },
];

export default products;
